name: notekeeper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  flutter_riverpod: ^2.5.1
  riverpod_generator: ^2.4.3
  riverpod_annotation: ^2.3.5
  gap: ^3.0.1
  shared_preferences: ^2.3.2
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
